```{r}
install.packages(c('DBI', 'bigrquery')) # already installed by fishwatchr
library(DBI)
library(bigrquery)

# install.packages("dplyr")
library(dplyr)
library(gfwr)
library(ggplot2)

# install.packages("sf")
library(sf)


con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)

```

# Round 1 - June 2024

## using gfwr to pull active vessels

```{r}
NPG_vessels_march_june <- read.csv2(file = here::here("data", "GFW_vesselpresence_mar1-june6.csv"), sep = ",",)


# try pulling vessel ids using gfwr

NPG_AOI <- sf::st_read( dsn = here::here("data", "Patrol1_Jun2024", "NPGgeometry.geojson" ))
NPG_AOI <- sf::st_read( dsn = here::here("data", "geometry_test.geojson" ))

# INPUT IS A PATH TO A FILE

# The user-defined geojson has to be surrounded by a geojson tag, that can be created using a simple paste:

# geojson_tagged <- paste0('{"geojson":', NPG_AOI,'}') # in documentation but nate provided other way

geojson_tagged <- gfwr::sf_to_geojson(NPG_AOI %>% dplyr::select(-bbox)) # nate's recommendation

NPG <- get_raster(spatial_resolution = "LOW",
           temporal_resolution = "DAILY",
           group_by = "VESSEL_ID",
           date_range = "2024-06-01,2024-06-07",
           region = geojson_tagged,
           region_source = "USER_JSON",
           key = gfw_auth())



NPG %>% select("Vessel ID", "Flag", "Vessel Name", "Gear Type", "Vessel Type", "MMSI", "IMO")
```

## look at overlap between original and better query
```{r}

jun1_6_vessels_new <- read.csv2(file = here::here("data", "GFW_AOI_list_new_jun1-6.csv"), sep = ",",)
jun1_6_vessels_old <- read.csv2(file = here::here("data", "GFW_AOI_list_old_jun1-6.csv"), sep = ",",)
jun10_16_vessels <- read.csv2(file = here::here("data", "GFW_AOI_list_jun10-16.csv"), sep = ",",)

setdiff(jun1_6_vessels_new$ssvid, jun1_6_vessels_old$ssvid)
setdiff(jun1_6_vessels_old$ssvid, jun1_6_vessels_new$ssvid)
setdiff(jun1_6_vessels_new$ssvid, jun10_16_vessels$ssvid)
setdiff(jun10_16_vessels$ssvid, jun1_6_vessels_new$ssvid)

# look at whether ssvid dupes
jun1_6_vessels_new %>% group_by(ssvid) %>% summarise(n_ssvid = n()) %>% arrange(n_ssvid) %>% View()

```

# Round 2 - Aug-Sept 2024

## comparing vessel lists from round 1 to 2 and some metrics
```{r}

# 3061 total vessels in AOI between 18jul-19aug 2024
# of those, 526 fv and cv
# AOI 6,521,832 km²

# import vessel lists
may1_jun1_vessels <- read.csv2(file = here::here("data", "Patrol1_Jun2024", "Patrol1_may1-jun1_ownershiptab.csv"), sep = ",",)
jul18_aug19_vessels <- read.csv2(file = here::here("data", "Patrol2_Aug2024", "from_map_fv_cv_18jul-19aug.csv"), sep = ",",)
jul16_aug16_hasfishevent <- read.csv2(file = here::here("data", "Patrol2_Aug2024", "NPG_fishingonly_Jul16-Aug16.csv"), sep = ",",)

# filter to just unique mmsi
jul18_aug19_vessels <- unique(jul18_aug19_vessels$mmsi)
may1_jun1_vessels <- unique(may1_jun1_vessels$MMSI)
# jul16_aug16_hasfishevent <- unique(jul16_aug16_hasfishevent$mmsi)

setdiff(may1_jun1_vessels, jul18_aug19_vessels) #42
setdiff(jul18_aug19_vessels, may1_jun1_vessels) #327

```
